require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - db/*
    - bin/*
    - lib/tasks/*
    - spec/cypress/app_commands/log_fail.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false